# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
  - stage: BuildAndPushAngularApp
    displayName: Build And Push Angular Application
    jobs:
      - job: BuildAndPushAngularApp
        pool: local-agent-task-06
        steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'Docker Registry'
            repository: 'umararafath/angular-social-network'
            command: 'buildAndPush'
            Dockerfile: 'Dockerfile'

